/**
 * Eurofurence API for Mobile Apps
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package org.eurofurence.data.models

import kotlinx.serialization.Serializable
import org.eurofurence.serial.LocalDateTimeSerializer

/**
 *
 * @param Since
 * @param CurrentDateTimeUtc
 * @param Events
 * @param EventConferenceDays
 * @param EventConferenceRooms
 * @param EventConferenceTracks
 * @param KnowledgeGroups
 * @param KnowledgeEntries
 * @param Images
 * @param Dealers
 * @param Announcements
 * @param Maps
 */
@Serializable
data class AggregatedDeltaResponse(
        @Serializable(with = LocalDateTimeSerializer::class)
        val Since: java.time.LocalDateTime? = null,
        @Serializable(with = LocalDateTimeSerializer::class)
        val CurrentDateTimeUtc: java.time.LocalDateTime? = null,
        val Events: DeltaResponseLeft_Square_BracketEventRecordRight_Square_Bracket? = null,
        val EventConferenceDays: DeltaResponseLeft_Square_BracketEventConferenceDayRecordRight_Square_Bracket? = null,
        val EventConferenceRooms: DeltaResponseLeft_Square_BracketEventConferenceRoomRecordRight_Square_Bracket? = null,
        val EventConferenceTracks: DeltaResponseLeft_Square_BracketEventConferenceTrackRecordRight_Square_Bracket? = null,
        val KnowledgeGroups: DeltaResponseLeft_Square_BracketKnowledgeGroupRecordRight_Square_Bracket? = null,
        val KnowledgeEntries: DeltaResponseLeft_Square_BracketKnowledgeEntryRecordRight_Square_Bracket? = null,
        val Images: DeltaResponseLeft_Square_BracketImageRecordRight_Square_Bracket? = null,
        val Dealers: DeltaResponseLeft_Square_BracketDealerRecordRight_Square_Bracket? = null,
        val Announcements: DeltaResponseLeft_Square_BracketAnnouncementRecordRight_Square_Bracket? = null,
        val Maps: DeltaResponseLeft_Square_BracketMapRecordRight_Square_Bracket? = null
) {

}

