/**
 * Eurofurence API for Mobile Apps
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package org.eurofurence.data.models

import kotlinx.serialization.Serializable
import org.eurofurence.serial.UUIDSerializer


/**
 *
 * @param Id
 * @param Name
 */
@Serializable
data class BadgeInfo(
        @Serializable(with = UUIDSerializer::class)
        val Id: java.util.UUID? = null,
        val Name: kotlin.String? = null
) {

}

