/**
 * Eurofurence API for Mobile Apps
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package org.eurofurence.data.models

import kotlinx.serialization.Serializable
import org.eurofurence.serial.UUIDSerializer


/**
 *
 * @param FursuitBadgeId
 * @param FursuitCollectionCount
 * @param Name
 * @param Species
 * @param Gender
 */
@Serializable
data class CollectTokenResponse(
        @Serializable(with = UUIDSerializer::class)
        val FursuitBadgeId: java.util.UUID? = null,
        val FursuitCollectionCount: kotlin.Int? = null,
        val Name: kotlin.String? = null,
        val Species: kotlin.String? = null,
        val Gender: kotlin.String? = null
) {

}

