/**
 * Eurofurence API for Mobile Apps
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package org.eurofurence.data.models

import kotlinx.serialization.Serializable
import org.eurofurence.serial.LocalDateTimeSerializer
import org.eurofurence.serial.UUIDSerializer

/**
 *
 * @param LastChangeDateTimeUtc
 * @param Id
 * @param RegistrationNumber
 * @param AttendeeNickname
 * @param DisplayName
 * @param Merchandise
 * @param ShortDescription
 * @param AboutTheArtistText
 * @param AboutTheArtText
 * @param Links
 * @param TwitterHandle
 * @param TelegramHandle
 * @param AttendsOnThursday
 * @param AttendsOnFriday
 * @param AttendsOnSaturday
 * @param ArtPreviewCaption
 * @param ArtistThumbnailImageId
 * @param ArtistImageId
 * @param ArtPreviewImageId
 */
@Serializable
data class DealerRecord(
        @Serializable(with = LocalDateTimeSerializer::class)
        val LastChangeDateTimeUtc: java.time.LocalDateTime,
        @Serializable(with = UUIDSerializer::class)
        val Id: java.util.UUID,
        val RegistrationNumber: kotlin.Int,
        val AttendeeNickname: kotlin.String,
        val DisplayName: kotlin.String,
        val Merchandise: kotlin.String,
        val Links: kotlin.Array<LinkFragment>,
        val ShortDescription: kotlin.String? = null,
        val AboutTheArtistText: kotlin.String? = null,
        val AboutTheArtText: kotlin.String? = null,
        val TwitterHandle: kotlin.String? = null,
        val TelegramHandle: kotlin.String? = null,
        val AttendsOnThursday: kotlin.Boolean? = null,
        val AttendsOnFriday: kotlin.Boolean? = null,
        val AttendsOnSaturday: kotlin.Boolean? = null,
        val ArtPreviewCaption: kotlin.String? = null,
        @Serializable(with = UUIDSerializer::class)
        val ArtistThumbnailImageId: java.util.UUID? = null,
        @Serializable(with = UUIDSerializer::class)
        val ArtistImageId: java.util.UUID? = null,
        @Serializable(with = UUIDSerializer::class)
        val ArtPreviewImageId: java.util.UUID? = null
) {

}

