/**
 * Eurofurence API for Mobile Apps
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package org.eurofurence.data.models

import kotlinx.serialization.Serializable


/**
 *
 * @param BadgeNo
 * @param RegNo
 * @param Name
 * @param WornBy
 * @param Species
 * @param Gender
 * @param ImageContent
 * @param DontPublish
 */
@Serializable
data class FursuitBadgeRegistration(
        val BadgeNo: kotlin.Int? = null,
        val RegNo: kotlin.Int? = null,
        val Name: kotlin.String? = null,
        val WornBy: kotlin.String? = null,
        val Species: kotlin.String? = null,
        val Gender: kotlin.String? = null,
        val ImageContent: kotlin.String? = null,
        val DontPublish: kotlin.Int? = null
) {

}

