/**
 * Eurofurence API for Mobile Apps
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package org.eurofurence.data.models

import kotlinx.serialization.Serializable
import org.eurofurence.serial.LocalDateTimeSerializer
import org.eurofurence.serial.UUIDSerializer


/**
 *
 * @param LastChangeDateTimeUtc
 * @param Id
 * @param ExternalReference
 * @param OwnerUid
 * @param Name
 * @param WornBy
 * @param Species
 * @param Gender
 * @param IsPublic
 */
@Serializable
data class FursuitBadgeRecord(
        @Serializable(with = LocalDateTimeSerializer::class)
        val LastChangeDateTimeUtc: java.time.LocalDateTime,
        @Serializable(with = UUIDSerializer::class)
        val Id: java.util.UUID,
        val OwnerUid: kotlin.String,
        val Name: kotlin.String,
        val WornBy: kotlin.String,
        val Species: kotlin.String,
        val Gender: kotlin.String,
        val ExternalReference: kotlin.String? = null,
        val IsPublic: kotlin.Boolean? = null
) {

}

