/**
 * Eurofurence API for Mobile Apps
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package org.eurofurence.data.models

import kotlinx.serialization.Serializable
import org.eurofurence.serial.LocalDateTimeSerializer
import org.eurofurence.serial.UUIDSerializer


/**
 *
 * @param LastChangeDateTimeUtc
 * @param Id
 * @param OwnerUid
 * @param FursuitBadgeId
 * @param TokenValue
 * @param IsBanned
 * @param TokenRegistrationDateTimeUtc
 * @param CollectionCount
 */
@Serializable
data class FursuitParticipationRecord(
        @Serializable(with = LocalDateTimeSerializer::class)
        val LastChangeDateTimeUtc: java.time.LocalDateTime,
        @Serializable(with = UUIDSerializer::class)
        val Id: java.util.UUID,
        val OwnerUid: kotlin.String? = null,
        @Serializable(with = UUIDSerializer::class)
        val FursuitBadgeId: java.util.UUID? = null,
        val TokenValue: kotlin.String? = null,
        val IsBanned: kotlin.Boolean? = null,
        @Serializable(with = LocalDateTimeSerializer::class)
        val TokenRegistrationDateTimeUtc: java.time.LocalDateTime? = null,
        val CollectionCount: kotlin.Int? = null
) {

}

