/**
 * Eurofurence API for Mobile Apps
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package org.eurofurence.data.models

import kotlinx.serialization.Serializable
import org.eurofurence.serial.LocalDateTimeSerializer
import org.eurofurence.serial.UUIDSerializer
import java.util.*

/**
 *
 * @param LastChangeDateTimeUtc
 * @param Id
 * @param ImageId
 * @param Description
 * @param IsBrowseable
 * @param Entries
 */
@Serializable
data class MapRecord(
        @Serializable(with = LocalDateTimeSerializer::class)
        val LastChangeDateTimeUtc: java.time.LocalDateTime,
        @Serializable(with = UUIDSerializer::class)
        val Id: java.util.UUID,
        @Serializable(with = UUIDSerializer::class)
        val ImageId: java.util.UUID,
        val Description: kotlin.String,
        val IsBrowseable: kotlin.Boolean,
        val Entries: kotlin.Array<MapEntryRecord>
) {
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as MapRecord

        if (LastChangeDateTimeUtc != other.LastChangeDateTimeUtc) return false
        if (Id != other.Id) return false
        if (ImageId != other.ImageId) return false
        if (Description != other.Description) return false
        if (IsBrowseable != other.IsBrowseable) return false
        if (!Arrays.equals(Entries, other.Entries)) return false

        return true
    }

    override fun hashCode(): Int {
        var result = LastChangeDateTimeUtc.hashCode()
        result = 31 * result + Id.hashCode()
        result = 31 * result + ImageId.hashCode()
        result = 31 * result + Description.hashCode()
        result = 31 * result + IsBrowseable.hashCode()
        result = 31 * result + Arrays.hashCode(Entries)
        return result
    }

}

