/**
 * Eurofurence API for Mobile Apps
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package org.eurofurence.data.models

import kotlinx.serialization.Serializable
import java.util.*


/**
 *
 * @param DeviceId
 * @param Topics
 */
@Serializable
data class PostFcmDeviceRegistrationRequest(
        val DeviceId: kotlin.String? = null,
        val Topics: kotlin.Array<kotlin.String>? = null
) {
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as PostFcmDeviceRegistrationRequest

        if (DeviceId != other.DeviceId) return false
        if (!Arrays.equals(Topics, other.Topics)) return false

        return true
    }

    override fun hashCode(): Int {
        var result = DeviceId?.hashCode() ?: 0
        result = 31 * result + (Topics?.let { Arrays.hashCode(it) } ?: 0)
        return result
    }

}

