/**
 * Eurofurence API for Mobile Apps
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package org.eurofurence.data.models

import kotlinx.serialization.Serializable


/**
 *
 * @param RecipientUid
 * @param AuthorName
 * @param ToastTitle
 * @param ToastMessage
 * @param Subject
 * @param Message
 */
@Serializable
data class SendPrivateMessageRequest(
        val RecipientUid: kotlin.String? = null,
        val AuthorName: kotlin.String? = null,
        val ToastTitle: kotlin.String? = null,
        val ToastMessage: kotlin.String? = null,
        val Subject: kotlin.String? = null,
        val Message: kotlin.String? = null
) {

}

